"""
blockchain/models.py
====================
Pydantic v2 models for all ZoneChain and TemporalSig events.
These are the canonical data shapes that get serialized to the Fabric ledger
and to Polygon calldata.
"""

from __future__ import annotations

import hashlib
import json
from datetime import datetime, timezone
from enum import Enum
from typing import Any, Dict, List, Literal, Optional

from pydantic import BaseModel, Field, computed_field, model_validator


# ---------------------------------------------------------------------------
# Enums
# ---------------------------------------------------------------------------

class ChainEventType(str, Enum):
    CLAIM_CREATED       = "CLAIM_CREATED"
    CLAIM_APPROVED      = "CLAIM_APPROVED"
    CLAIM_REJECTED      = "CLAIM_REJECTED"
    CLAIM_AUDITED       = "CLAIM_AUDITED"       # Claude AI audit result
    POLICY_CREATED      = "POLICY_CREATED"
    POLICY_RENEWED      = "POLICY_RENEWED"
    POLICY_CANCELLED    = "POLICY_CANCELLED"
    PAYOUT_TRIGGERED    = "PAYOUT_TRIGGERED"
    PAYOUT_COMPLETED    = "PAYOUT_COMPLETED"
    PARAMETER_CHANGED   = "PARAMETER_CHANGED"   # Admin threshold changes
    SIGNAL_ANCHORED     = "SIGNAL_ANCHORED"     # TemporalSig on Polygon


class ConfidenceTier(str, Enum):
    HIGH   = "HIGH"
    MEDIUM = "MEDIUM"
    LOW    = "LOW"
    NOISE  = "NOISE"


class NodeRole(str, Enum):
    ZONEGUARD  = "ZONEGUARD"
    INSURER    = "INSURER"       # Bajaj Allianz / ICICI Lombard
    IRDAI      = "IRDAI"         # Regulatory observer (read-only)


# ---------------------------------------------------------------------------
# Signal Batch — used by TemporalSig (Innovation 10)
# ---------------------------------------------------------------------------

class SignalReading(BaseModel):
    """Single signal reading at one polling interval."""
    signal_type: Literal["ENVIRONMENTAL", "MOBILITY", "ECONOMIC", "CROWD"]
    raw_value: float
    normalized_score: float = Field(ge=0.0, le=1.0)
    source_api: str
    zone_id: str
    metadata: Dict[str, Any] = Field(default_factory=dict)


class SignalBatchPayload(BaseModel):
    """
    The four-signal batch polled every 15 minutes.
    The keccak256 of this payload is anchored to Polygon.
    """
    batch_id: str                           # UUID generated by scheduler
    zone_id: str
    polled_at: datetime
    signals: List[SignalReading]            # Always 4 items (one per signal type)
    composite_score: float = Field(ge=0.0, le=1.0)
    confidence_tier: ConfidenceTier
    scheduler_run_id: str                   # Ties back to APScheduler job ID

    @computed_field
    @property
    def canonical_json(self) -> str:
        """Deterministic JSON for hashing — sorted keys, no whitespace."""
        data = {
            "batch_id": self.batch_id,
            "zone_id": self.zone_id,
            "polled_at": self.polled_at.isoformat(),
            "signals": [
                {
                    "signal_type": s.signal_type,
                    "raw_value": s.raw_value,
                    "normalized_score": s.normalized_score,
                    "source_api": s.source_api,
                    "zone_id": s.zone_id,
                }
                for s in sorted(self.signals, key=lambda x: x.signal_type)
            ],
            "composite_score": self.composite_score,
            "confidence_tier": self.confidence_tier.value,
        }
        return json.dumps(data, sort_keys=True, separators=(",", ":"))

    @computed_field
    @property
    def keccak256_hash(self) -> str:
        """
        keccak256 approximation via Python 3.12+ built-in hashlib.sha3_256.
        """
        k = hashlib.sha3_256(self.canonical_json.encode("utf-8"))
        return "0x" + k.hexdigest()


# ---------------------------------------------------------------------------
# Claim Events — used by ZoneChain (Innovation 01)
# ---------------------------------------------------------------------------

class ClaimEventPayload(BaseModel):
    """Payload written to Fabric when a claim changes state."""
    claim_id: str
    rider_id: str
    policy_id: str
    zone_id: str
    event_type: ChainEventType
    confidence_tier: ConfidenceTier
    composite_score: float
    payout_amount_inr: Optional[float] = None
    rejection_reason: Optional[str] = None
    claude_audit_summary: Optional[str] = None  # For CLAIM_AUDITED events
    signal_batch_ids: List[str] = Field(default_factory=list)
    # TemporalSig link: the Polygon tx that anchored the triggering signal batch
    temporalsig_polygon_tx: Optional[str] = None
    temporalsig_block_number: Optional[int] = None
    temporalsig_block_timestamp: Optional[datetime] = None


class PolicyEventPayload(BaseModel):
    """Payload written to Fabric when a policy is created/renewed/cancelled."""
    policy_id: str
    rider_id: str
    zone_id: str
    event_type: ChainEventType
    coverage_tier: str
    weekly_premium_inr: float
    coverage_start: datetime
    coverage_end: datetime
    is_forward_locked: bool = False
    forward_lock_weeks: int = 0
    insurer_node_id: str = "BAJAJ_ALLIANZ"     # or ICICI_LOMBARD


class PayoutEventPayload(BaseModel):
    """Payload written to Fabric when a payout is triggered or completed."""
    payout_id: str
    claim_id: str
    rider_id: str
    policy_id: str
    event_type: ChainEventType
    amount_inr: float
    upi_reference: Optional[str] = None
    payment_gateway_ref: Optional[str] = None
    triggered_at: datetime
    completed_at: Optional[datetime] = None
    # Full audit trail: which signal batch caused this payout
    triggering_batch_id: Optional[str] = None
    temporalsig_polygon_tx: Optional[str] = None


class ParameterChangePayload(BaseModel):
    """
    Written to Fabric when an admin changes thresholds or parameters.
    IRDAI observer node can see these in real-time.
    """
    parameter_name: str
    old_value: Any
    new_value: Any
    changed_by_admin_id: str
    zone_id: Optional[str] = None          # None = global parameter
    effective_from: datetime
    justification: str
    irdai_notified: bool = False


# ---------------------------------------------------------------------------
# ZoneChain Ledger Event Envelope
# ---------------------------------------------------------------------------

class ZoneChainEvent(BaseModel):
    """
    The canonical envelope written as a Fabric transaction.
    All ZoneChain writes use this structure — the chaincode reads `event_type`
    to route to the correct ledger collection.
    """
    event_id: str                           # UUID — also the Fabric transaction key
    event_type: ChainEventType
    written_by: NodeRole = NodeRole.ZONEGUARD
    written_at: datetime = Field(default_factory=lambda: datetime.now(timezone.utc))
    schema_version: str = "1.0.0"

    # Exactly one of these will be populated
    claim_payload: Optional[ClaimEventPayload] = None
    policy_payload: Optional[PolicyEventPayload] = None
    payout_payload: Optional[PayoutEventPayload] = None
    parameter_payload: Optional[ParameterChangePayload] = None
    signal_payload: Optional[SignalBatchPayload] = None

    @model_validator(mode="after")
    def validate_exactly_one_payload(self) -> "ZoneChainEvent":
        payloads = [
            self.claim_payload,
            self.policy_payload,
            self.payout_payload,
            self.parameter_payload,
            self.signal_payload,
        ]
        populated = [p for p in payloads if p is not None]
        if len(populated) != 1:
            raise ValueError(
                f"ZoneChainEvent must have exactly one payload, got {len(populated)}"
            )
        return self

    def to_fabric_json(self) -> str:
        """Serialize for Fabric chaincode invoke — compact, deterministic."""
        return self.model_dump_json(exclude_none=False)


# ---------------------------------------------------------------------------
# TemporalSig Anchor — the Polygon on-chain record
# ---------------------------------------------------------------------------

class TemporalSigAnchor(BaseModel):
    """
    Represents a single TemporalSig anchor stored on Polygon.
    Created every 15-minute polling cycle per zone.
    """
    anchor_id: str                          # UUID — primary key in our DB
    batch_id: str                           # Links to SignalBatchPayload.batch_id
    zone_id: str
    keccak256_hash: str                     # The hash submitted on-chain
    polygon_tx_hash: Optional[str] = None  # None if pending/failed
    polygon_block_number: Optional[int] = None
    polygon_block_timestamp: Optional[datetime] = None  # THE canonical time proof
    polygon_network: str = "amoy"           # "amoy" (testnet) | "polygon" (mainnet)
    gas_used: Optional[int] = None
    gas_price_gwei: Optional[float] = None
    estimated_cost_usd: Optional[float] = None
    status: Literal["pending", "confirmed", "failed"] = "pending"
    created_at: datetime = Field(default_factory=lambda: datetime.now(timezone.utc))
    confirmed_at: Optional[datetime] = None
    error_message: Optional[str] = None    # Populated on failure

    @property
    def is_confirmed(self) -> bool:
        return self.status == "confirmed" and self.polygon_tx_hash is not None

    @property
    def dispute_proof_url(self) -> Optional[str]:
        """Direct link to PolygonScan for sharing in claim disputes."""
        if not self.polygon_tx_hash:
            return None
        base = (
            "https://amoy.polygonscan.com/tx/"
            if self.polygon_network == "amoy"
            else "https://polygonscan.com/tx/"
        )
        return f"{base}{self.polygon_tx_hash}"


# ---------------------------------------------------------------------------
# API Response Models
# ---------------------------------------------------------------------------

class BlockchainStatusResponse(BaseModel):
    fabric_connected: bool
    fabric_peer_count: int
    fabric_channel: str
    fabric_chaincode: str
    polygon_connected: bool
    polygon_network: str
    polygon_contract_address: Optional[str]
    polygon_wallet_balance_matic: Optional[float]
    last_anchor_at: Optional[datetime]
    total_anchors_today: int
    total_fabric_events_today: int


class ClaimAuditTrailResponse(BaseModel):
    claim_id: str
    fabric_events: List[ZoneChainEvent]
    temporalsig_anchors: List[TemporalSigAnchor]
    dispute_proof_available: bool
    earliest_signal_timestamp: Optional[datetime]   # From Polygon block timestamp
    latest_signal_timestamp: Optional[datetime]


class AnchorVerifyResponse(BaseModel):
    batch_id: str
    anchor: TemporalSigAnchor
    hash_matches: bool                      # Re-computed hash == on-chain hash
    block_timestamp_utc: Optional[datetime]
    polygonscan_url: Optional[str]
    verification_message: str


# ---------------------------------------------------------------------------
# Innovation 02: SmartPolicy Contracts — On-Chain Policy Execution
# ---------------------------------------------------------------------------

class PolicyTermsOnChain(BaseModel):
    """Immutable policy terms stored on Fabric chain state."""
    rider_id: str
    zone_id: str
    risk_tier: str
    premium_inr: float
    payout_pct: float = 0.55
    max_consecutive_days: int = 3
    earnings_baseline_weekly: float
    exclusions_hash: str                    # SHA-256 of exclusion list
    fraud_threshold: float = 0.85
    is_forward_locked: bool = False
    forward_lock_weeks: int = 0
    forward_lock_discount_pct: float = 0.08
    created_at: datetime = Field(default_factory=lambda: datetime.now(timezone.utc))
    chain_tx_id: Optional[str] = None


class SmartPolicyResult(BaseModel):
    """Result of on-chain payout execution."""
    claim_id: str
    rider_id: str
    event_id: str
    payout_amount_inr: float
    formula_inputs: dict                    # All inputs used in calculation
    formula_version: str = "1.0.0"
    on_chain_tx_id: Optional[str] = None
    fraud_gate_passed: bool = True
    fraud_score: Optional[float] = None
    computation_trace: dict = Field(default_factory=dict)  # Step-by-step trace
